Embed git diff --check in pre-commit hook

diff --git a/hooks/pre-commit b/hooks/pre-commit
--- a/hooks/pre-commit
+++ b/hooks/pre-commit
@@ -74,3 +74,7 @@ run() {
 
 files=($(git diff --name-only --diff-filter=AM --cached HEAD))
 run "${files[@]}"
+
+if ! git diff --check --cached; then
+    fatal 'hook abort: `git diff --check` reports issues'
+fi
